### ISSUE TITLE
no results

### ISSUE THREAD

**Issue by airsimonhan** [edouardoyallon/scalingscattering#4]
hi ! thanks for your great job !
I debugede your code , but after this result:
"Total number of parameters: 12777726.000000"
the code stopped running,I waited for a few hours ,but still haven't any change, do you know the reason?

**Comment by edouardoyallon** [comment]
Hi,

Thanks for your message. Maybe you could be more specific? Like with a gist or something similar. As pytorch changed a lot, there might be indeed some incompatibility...

Best,
Edouard

**Comment by airsimonhan** [comment]
> Hi,
> 
> Thanks for your message. Maybe you could be more specific? Like with a gist or something similar. As pytorch changed a lot, there might be indeed some incompatibility...
> 
> Best,
> Edouard

runfile('/home/han/scalingscattering-master/imagenet/main_test.py', wdir='/home/han/scalingscattering-master/imagenet')
('parsed options:', {'imagenetpath': 'dataset/', 'resume': 'scatter_resnet_10_model.pt7', 'batchSize': 256, 'gpu_id': '0', 'nthread': 4, 'N': 224, 'ngpu': 1, 'model': 'scatresnet6_2', 'scat': 3})
3
217
28
| setting up data loader...
('model was restored from epoch:', 0)
Parameters:
                                     0           ...                                 2
0                     bn0.running_mean           ...            torch.cuda.FloatTensor
1                      bn0.running_var           ...            torch.cuda.FloatTensor
2                         conv1.weight           ...            torch.cuda.FloatTensor
3                           conv1.bias           ...            torch.cuda.FloatTensor
4                           bn1.weight           ...            torch.cuda.FloatTensor
5                             bn1.bias           ...            torch.cuda.FloatTensor
6                     bn1.running_mean           ...            torch.cuda.FloatTensor
7                      bn1.running_var           ...            torch.cuda.FloatTensor
8                layer1.0.conv1.weight           ...            torch.cuda.FloatTensor
9                  layer1.0.bn1.weight           ...            torch.cuda.FloatTensor
10                   layer1.0.bn1.bias           ...            torch.cuda.FloatTensor
11           layer1.0.bn1.running_mean           ...            torch.cuda.FloatTensor
12            layer1.0.bn1.running_var           ...            torch.cuda.FloatTensor
13               layer1.0.conv2.weight           ...            torch.cuda.FloatTensor
14                 layer1.0.bn2.weight           ...            torch.cuda.FloatTensor
15                   layer1.0.bn2.bias           ...            torch.cuda.FloatTensor
16           layer1.0.bn2.running_mean           ...            torch.cuda.FloatTensor
17            layer1.0.bn2.running_var           ...            torch.cuda.FloatTensor
18               layer1.1.conv1.weight           ...            torch.cuda.FloatTensor
19                 layer1.1.bn1.weight           ...            torch.cuda.FloatTensor
20                   layer1.1.bn1.bias           ...            torch.cuda.FloatTensor
21           layer1.1.bn1.running_mean           ...            torch.cuda.FloatTensor
22            layer1.1.bn1.running_var           ...            torch.cuda.FloatTensor
23               layer1.1.conv2.weight           ...            torch.cuda.FloatTensor
24                 layer1.1.bn2.weight           ...            torch.cuda.FloatTensor
25                   layer1.1.bn2.bias           ...            torch.cuda.FloatTensor
26           layer1.1.bn2.running_mean           ...            torch.cuda.FloatTensor
27            layer1.1.bn2.running_var           ...            torch.cuda.FloatTensor
28               layer2.0.conv1.weight           ...            torch.cuda.FloatTensor
29                 layer2.0.bn1.weight           ...            torch.cuda.FloatTensor
30                   layer2.0.bn1.bias           ...            torch.cuda.FloatTensor
31           layer2.0.bn1.running_mean           ...            torch.cuda.FloatTensor
32            layer2.0.bn1.running_var           ...            torch.cuda.FloatTensor
33               layer2.0.conv2.weight           ...            torch.cuda.FloatTensor
34                 layer2.0.bn2.weight           ...            torch.cuda.FloatTensor
35                   layer2.0.bn2.bias           ...            torch.cuda.FloatTensor
36           layer2.0.bn2.running_mean           ...            torch.cuda.FloatTensor
37            layer2.0.bn2.running_var           ...            torch.cuda.FloatTensor
38        layer2.0.downsample.0.weight           ...            torch.cuda.FloatTensor
39        layer2.0.downsample.1.weight           ...            torch.cuda.FloatTensor
40          layer2.0.downsample.1.bias           ...            torch.cuda.FloatTensor
41  layer2.0.downsample.1.running_mean           ...            torch.cuda.FloatTensor
42   layer2.0.downsample.1.running_var           ...            torch.cuda.FloatTensor
43               layer2.1.conv1.weight           ...            torch.cuda.FloatTensor
44                 layer2.1.bn1.weight           ...            torch.cuda.FloatTensor
45                   layer2.1.bn1.bias           ...            torch.cuda.FloatTensor
46           layer2.1.bn1.running_mean           ...            torch.cuda.FloatTensor
47            layer2.1.bn1.running_var           ...            torch.cuda.FloatTensor
48               layer2.1.conv2.weight           ...            torch.cuda.FloatTensor
49                 layer2.1.bn2.weight           ...            torch.cuda.FloatTensor
50                   layer2.1.bn2.bias           ...            torch.cuda.FloatTensor
51           layer2.1.bn2.running_mean           ...            torch.cuda.FloatTensor
52            layer2.1.bn2.running_var           ...            torch.cuda.FloatTensor
53                           fc.weight           ...            torch.cuda.FloatTensor
54                             fc.bias           ...            torch.cuda.FloatTensor
[55 rows x 3 columns]
Additional buffers:
Empty DataFrame
Columns: []
Index: []
Total number of parameters: 12777726.000000
-------------------------------------------------------
then the program stopped running and no errors appered.

**Comment by edouardoyallon** [comment]
do you have a SSD?

**Comment by airsimonhan** [comment]
> do you have a SSD?

yes

**Comment by eugenium** [comment]
What version of pytorch are you on?

Also would it be possible to run the pyscatwave unit tests https://github.com/edouardoyallon/pyscatwave/tree/master/test to make sure the pyscatwave is properly installed

**Comment by airsimonhan** [comment]
> What version of pytorch are you on?
> 
> Also would it be possible to run the pyscatwave unit tests https://github.com/edouardoyallon/pyscatwave/tree/master/test to make sure the pyscatwave is properly installed



> What version of pytorch are you on?
> 
> Also would it be possible to run the pyscatwave unit tests https://github.com/edouardoyallon/pyscatwave/tree/master/test to make sure the pyscatwave is properly installed

>>> print scat(x).size()
0-3-4-40-40-periodize.cu
modulus.cu
0-3-2-40-40-periodize.cu
0-3-2-20-20-periodize.cu
(1, 3, 81, 8, 8)

**Comment by airsimonhan** [comment]
> do you have a SSD?

dataset/val/50000 ILSVRC2012

**Comment by airsimonhan** [comment]
CLFAR codes

47               layer3.1.conv1.weight           ...            torch.cuda.FloatTensor
48                 layer3.1.bn1.weight           ...            torch.cuda.FloatTensor
49                   layer3.1.bn1.bias           ...            torch.cuda.FloatTensor
50           layer3.1.bn1.running_mean           ...            torch.cuda.FloatTensor
51            layer3.1.bn1.running_var           ...            torch.cuda.FloatTensor
52               layer3.1.conv2.weight           ...            torch.cuda.FloatTensor
53                 layer3.1.bn2.weight           ...            torch.cuda.FloatTensor
54                   layer3.1.bn2.bias           ...            torch.cuda.FloatTensor
55           layer3.1.bn2.running_mean           ...            torch.cuda.FloatTensor
56            layer3.1.bn2.running_var           ...            torch.cuda.FloatTensor
57                           fc.weight           ...            torch.cuda.FloatTensor
58                             fc.bias           ...            torch.cuda.FloatTensor
[59 rows x 3 columns]
Additional buffers:
Empty DataFrame
Columns: []
Index: []
Total number of parameters: 10787184.000000
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/han/pycharm-2018.2.3/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/han/scalingscattering-master/CIFAR/main_small_sample_class_normalized.py", line 319, in <module>
    main()
  File "/home/han/scalingscattering-master/CIFAR/main_small_sample_class_normalized.py", line 315, in main
    engine.train(h, iter_train, opt.epochs, optimizer)
  File "/home/han/anaconda3/envs/python27/lib/python2.7/site-packages/torchnet/engine/engine.py", line 47, in train
    for sample in state['iterator']:
  File "/home/han/anaconda3/envs/python27/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/home/han/anaconda3/envs/python27/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/home/han/anaconda3/envs/python27/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/han/anaconda3/envs/python27/lib/python2.7/site-packages/torchnet/dataset/transformdataset.py", line 50, in __getitem__
    z[k] = transform(z[k])
  File "/home/han/anaconda3/envs/python27/lib/python2.7/site-packages/torchnet/transform.py", line 13, in composition
    z = tr(z)
  File "/home/han/scalingscattering-master/cvtransforms.py", line 107, in __call__
    x1 = random.randint(0, w - tw)
  File "/home/han/anaconda3/envs/python27/lib/python2.7/random.py", line 244, in randint
    return self.randrange(a, b+1)
  File "/home/han/anaconda3/envs/python27/lib/python2.7/random.py", line 220, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,-20, -20)

**Comment by eugenium** [comment]
Could you try to find the pytorch version you are using, unfortunatley pytorch and torchvision has changed quite a lot since the release of this code. 

something like this should work
>>> import torch; torch.__version__

**Comment by airsimonhan** [comment]
> Could you try to find the pytorch version you are using, unfortunatley pytorch and torchvision has changed quite a lot since the release of this code.
> 
> something like this should work
> 
> > > > import torch; torch.**version**

pytorch 0.4.0 torchversion0.2.1

maybe the problem is the version of packages?

**Comment by nshervt** [comment]
I am getting the same error for CIFAR code using kymatio.

```
Traceback (most recent call last):
  File "/Users/Nsherv/Desktop/scalingscattering-master/CIFAR/main_small_sample_class_normalized.py", line 326, in <module>
    main()
  File "/Users/Nsherv/Desktop/scalingscattering-master/CIFAR/main_small_sample_class_normalized.py", line 322, in main
    engine.train(h, iter_train, opt.epochs, optimizer)
  File "/Users/Nsherv/anaconda3/lib/python3.7/site-packages/torchnet/engine/engine.py", line 47, in train
    for sample in state['iterator']:
  File "/Users/Nsherv/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/Users/Nsherv/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/Users/Nsherv/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/Users/Nsherv/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/Users/Nsherv/anaconda3/lib/python3.7/site-packages/torchnet/dataset/transformdataset.py", line 50, in __getitem__
    z[k] = transform(z[k])
  File "/Users/Nsherv/anaconda3/lib/python3.7/site-packages/torchnet/transform.py", line 13, in composition
    z = tr(z)
  File "/Users/Nsherv/Desktop/scalingscattering-master/cvtransforms.py", line 109, in __call__
    x1 = random.randint(0, w - tw)
  File "/Users/Nsherv/anaconda3/lib/python3.7/random.py", line 222, in randint
    return self.randrange(a, b+1)
  File "/Users/Nsherv/anaconda3/lib/python3.7/random.py", line 200, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0,-20, -20)
```

How did you resolve the issue?
