### ISSUE TITLE
excellent jod!!!

### ISSUE THREAD

**Issue by airsimonhan** [edouardoyallon/scalingscattering#5]
Test [0,195/196] ; loss: 18.256 (17.631) ; err5: 98.75 (99.62) ; err1: 100.00 (99.91) ; data 0.013 ; time 1.792 [99.908, 99.622]

**Comment by edouardoyallon** [comment]
?

**Comment by airsimonhan** [comment]
> ?

if I want to train my owe model, how to modify the code?

**Comment by edouardoyallon** [comment]
This is a very old code, we did not release the training procedure. You can use the script here: https://github.com/pytorch/examples/blob/master/imagenet/main.py and you modify the line: https://github.com/pytorch/examples/blob/master/imagenet/main.py#L216 such that it incorporates the scattering transform. You have to employ models with appropriate input size.
